
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 25 17:26:18 CEST 2021
//----------------------------------------------------

package tiny1.analizadorsintactico.asc;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int POR = 50;
  public static final int LLCIE = 39;
  public static final int GE = 54;
  public static final int CAP = 40;
  public static final int CCIE = 41;
  public static final int INT = 6;
  public static final int PUNTOCOMA = 44;
  public static final int WRITE = 33;
  public static final int NOT = 15;
  public static final int AND = 13;
  public static final int LT = 55;
  public static final int IGUAL = 47;
  public static final int RECORD = 26;
  public static final int LLAP = 38;
  public static final int TYPE = 25;
  public static final int OR = 14;
  public static final int BOOL = 8;
  public static final int CALL = 24;
  public static final int DIV = 51;
  public static final int IF = 17;
  public static final int ENDWHILE = 23;
  public static final int PTR = 29;
  public static final int LE = 56;
  public static final int OF = 28;
  public static final int EOF = 0;
  public static final int AMP = 46;
  public static final int TRUE = 9;
  public static final int PCIE = 37;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int CADENA = 5;
  public static final int MENOS = 49;
  public static final int NULL = 12;
  public static final int MOD = 52;
  public static final int EQ = 57;
  public static final int REAL = 11;
  public static final int ENT = 3;
  public static final int PAP = 36;
  public static final int FLECHA = 45;
  public static final int ENDIF = 20;
  public static final int ELSE = 19;
  public static final int PUNTO = 43;
  public static final int NL = 35;
  public static final int READ = 32;
  public static final int IDEN = 2;
  public static final int WHILE = 21;
  public static final int DEL = 31;
  public static final int THEN = 18;
  public static final int SEPSECCION = 59;
  public static final int NE = 58;
  public static final int ARR = 27;
  public static final int LREAL = 4;
  public static final int PROC = 16;
  public static final int STRING = 7;
  public static final int FALSE = 10;
  public static final int GT = 53;
  public static final int VAR = 34;
  public static final int DO = 22;
  public static final int MAS = 48;
}

