/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoDescConstants.java */
package tiny1.analizadorsintactico.desc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoDescConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETRA = 50;
  /** RegularExpression Id. */
  int DIGP = 51;
  /** RegularExpression Id. */
  int DIG = 52;
  /** RegularExpression Id. */
  int PARTEENT = 53;
  /** RegularExpression Id. */
  int PARTEDEC = 54;
  /** RegularExpression Id. */
  int ENT = 55;
  /** RegularExpression Id. */
  int LREAL = 56;
  /** RegularExpression Id. */
  int INT = 57;
  /** RegularExpression Id. */
  int STRING = 58;
  /** RegularExpression Id. */
  int BOOL = 59;
  /** RegularExpression Id. */
  int TRUE = 60;
  /** RegularExpression Id. */
  int FALSE = 61;
  /** RegularExpression Id. */
  int REAL = 62;
  /** RegularExpression Id. */
  int NULL = 63;
  /** RegularExpression Id. */
  int IDEN = 64;
  /** RegularExpression Id. */
  int CADENA = 65;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"&&\"",
    "\";\"",
    "\"var\"",
    "\"type\"",
    "\"proc\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"array\"",
    "\"[\"",
    "\"]\"",
    "\"of\"",
    "\"record\"",
    "\"{\"",
    "\"}\"",
    "\"pointer\"",
    "\"if\"",
    "\"then\"",
    "\"endif\"",
    "\"else\"",
    "\"nl\"",
    "\"=\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"read\"",
    "\"write\"",
    "\"new\"",
    "\"delete\"",
    "\"call\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\".\"",
    "\"->\"",
    "<token of kind 48>",
    "<token of kind 49>",
    "<LETRA>",
    "<DIGP>",
    "<DIG>",
    "<PARTEENT>",
    "<PARTEDEC>",
    "<ENT>",
    "<LREAL>",
    "\"int\"",
    "\"string\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"real\"",
    "\"null\"",
    "<IDEN>",
    "<CADENA>",
  };

}
